### ISSUE TITLE
shareable URL for social media

### ISSUE THREAD

**Issue by RupertAvery** [OSSPhilippines/philippine-map-app#18]
Right now, the user needs to save the image in order to share on facebook. It could be possible to encode the users selections in a compact URL-encoded format, maybe compacted JSON as a base64-encoded string, then you could create a facebook app, and allow users to share the url via your facebook app.

People clicking the link will be shown a pre-populated map, based on the data contained in the URL.

The URL would be anonymous, you don't put any personal info.

Letting the user visit the page will also encourage interaction from the visitor.

**Comment by warengonzaga** [comment]
Hey, @RupertAvery good suggestion, I think what you are looking for is a way to share your data besides the saved image but in a form of a URL for ppl to view it.

**Comment by warengonzaga** [comment]
hey @gballesteros10, feel free to contribute, don't hesitate to help, we're open for contributions. If you have some idea on how to accomplish this let us know. Fork the project, create a branch for your changes let's say "feat/#18" - feature issue #18 something like that. After that push your code to your repo and then open PR. Hope this helps!

**Comment by gballesteros10** [comment]
great. thank you @warengonzaga , will try to find some time for this cool project.

**Comment by gballesteros10** [comment]
![2023-04-19 20_02_39-My Philippines Travel Level](https://user-images.githubusercontent.com/19832210/233073679-d110c909-70ad-4d46-9253-af4888a47ce4.png)

will create a PR, or draft, probably tomorrow. but basically base64 decode and encode is now working.

remaining issue: on mouse enter & leave, the fills are getting changed (to gray, then reset to white) when the levels are from URL params

**Comment by RupertAvery** [comment]
Aside from a URL, you could also store the data in localStorage so users can return to their map and edit / update it

**Comment by jofftiquez** [comment]
> ![2023-04-19 20_02_39-My Philippines Travel Level](https://user-images.githubusercontent.com/19832210/233073679-d110c909-70ad-4d46-9253-af4888a47ce4.png)
> 
> will create a PR, or draft, probably tomorrow. but basically base64 decode and encode is now working.
> 
> remaining issue: on mouse enter & leave, the fills are getting changed (to gray, then reset to white) when the levels are from URL params

While this will work, please consider the length of the `base64` encoded string if all objects in the map are marked with a color. Some anti-virus will detect such long URLs as "malicious". Can you do a test for this? Like, how long will the base64 string be? Thanks

**Comment by RupertAvery** [comment]
suppose you have encoded the selection as a json object { "XX" : "Y", ... } where XX is a number 1-82 and Y is a value 0-5, with whitespace in between you are looking at around 970+ characters if all 82 provinces are marked. Base64 encoding gets you 1300+ characters, well under the 2048 char url limit.

It still may be a bit much. 

@gballesteros10, how did you encode the user selection into base64?

**Comment by gballesteros10** [comment]
@jofftiquez @RupertAvery yeah, right after testing a couple places, i worried about the length too. honestly right now i just want to make it work, then i'll tackle optimizing the string length after (or leave it to you guys haha)

@RupertAvery thanks for pointing me to RLE, i will look into it.

also thanks for the `replaceState` suggestion, it'll be a nice addition. i'll probably use a function from react router though.

anyway, mouse enter/leave issue is fixed. moved the hover styling to css instead of `event.target.setAttribute("fill"...)`

i'll get back on this tomorrow.

**Comment by RupertAvery** [comment]
If you look at the japan version, it actually just encodes it directly in the url as a series of numbers:

https://zhung.com.tw/japanex/#00000000000000000000000000000000000002000025002

Changing the selections updates the url directly.

In this case, base64 isn't needed anymore, since encoding to base64 actually makes it larger.

**Comment by jofftiquez** [comment]
> If you look at the japan version, it actually just encodes it directly in the url as a series of numbers:
> 
> [zhung.com.tw/japanex/#00000000000000000000000000000000000002000025002](https://zhung.com.tw/japanex/#00000000000000000000000000000000000002000025002)
> 
> Changing the selections updates the url directly.
> 
> In this case, base64 isn't needed anymore, since encoding to base64 actually makes it larger.
> 
> It also has a Share FB button

Cool, this is actually better and smaller. You can just designate each provinces a position on the string like so:

`00000`

Say first `0` is Quezon, 2nd `0` is Metro Manila, 3rd `0` is Bicol, and so on. If the level for Quezon is 5, then the string should be:

`50000`

Which makes the url `https://<domain>.com?levels=50000`

You can then just split the string when "decoding".

**Comment by gballesteros10** [comment]
@RupertAvery @jofftiquez that makes more sense and a lot more straightforward. thank you.

i don't think we already have an array where the provinces are sorted in proper order, to which we'll base the indexes of the `levels?=43250210`

and while we're here, is there a reason as to why the `<path>`s are hardcoded in `PhilippinesMapJSX.jsx`? is the svg generated from somewhere and we shouldn't touch it? it's a long list and makes the code look cluttered.

when implementing this provinces with an order, i might as well create an obj array of provinces which contains `name, coordinates, etc` then just do `provinceArr.map(prov => <path...>)`

i'm at work atm so i'll do this later in the evening.

**Comment by jofftiquez** [comment]
@gballesteros10 @RupertAvery 

Noted on the comments 

Re: A new array of provinces. 

An array would be ok but I think using Map would be better. Since all data are predetermined we can achieve `O(1)` time complexity with Map instead of `O(n)` with Array.

**Comment by denzdelvillar** [comment]
> and while we're here, is there a reason as to why the <path>s are hardcoded in PhilippinesMapJSX.jsx? is the svg generated from somewhere and we shouldn't touch it? it's a long list and makes the code look cluttered.


Hi @gballesteros10! I used [vectr](https://vectr.com/) to generate the svg then eventually moved to inkscape to edit further. Feel free to make the code look less cluttered.

>If you look at the japan version, it actually just encodes it directly in the url as a series of numbers:
>
> https://zhung.com.tw/japanex/#00000000000000000000000000000000000002000025002
>
> Changing the selections updates the url directly.
>
> In this case, base64 isn't needed anymore, since encoding to base64 actually makes it larger.
>
> It also has a Share FB button

Yes, this was how I wanted to implement a saving mechanism. I just didn't know how to do it so thank you everyone for taking the initiative!

**Comment by gballesteros10** [comment]
hi @denzdelvillar ! got it. thanks for starting this project 😁

**Comment by jofftiquez** [comment]
@gballesteros10 here's an example of how it could go. One improvement here is to update the algorithm for searching the places in a given list. Like I suggested above, we can use hash map for `O(1)` search.

https://jsfiddle.net/greenfoxx/n6v7d1m5/132/

**Comment by gballesteros10** [comment]
hi @jofftiquez !

sorry i saw your comment late. i'm almost already done with the implementation, i had a slightly different approach. but thank you.

i'd say it's working now but i haven't tested it much yet. and personally would like to still do some cleanup and maybe also work on your comment regarding time complexity.

but i will already make a PR just so you guys can see a preview build.

thanks!

**Comment by gballesteros10** [comment]
hi @jofftiquez i took a different route. didn't use hash map but still avoided `O(n)` (as far as i know) since i didn't create a key value pair of `{provinceName, level}` anymore. therefore not using province name as key when changing a value.

i used index instead and directly accessed the values, no need to find from array, no `O(n)`. we need a strict of provinces anyway so might as well use the index as identifiers.

**Comment by jofftiquez** [comment]
> hi @jofftiquez !
> 
> sorry i saw your comment late. i'm almost already done with the implementation, i had a slightly different approach. but thank you.
> 
> i'd say it's working now but i haven't tested it much yet. and personally would like to still do some cleanup and maybe also work on your comment regarding time complexity.
> 
> but i will already make a PR just so you guys can see a preview build.
> 
> thanks!

All goods, no problem.

**Comment by gballesteros10** [comment]
many thanks @jofftiquez ! will address the comments in a bit.

btw, to see the preview build, am i authorized to allow the deployment in the PR, and should I? or will it be done from your side?

**Comment by warengonzaga** [comment]
> many thanks @jofftiquez ! will address the comments in a bit.
> 
> btw, to see the preview build, am i authorized to allow the deployment in the PR, and should I? or will it be done from your side?

For the deployment preview, yes we should authorize it feel free to tag me or @jofftiquez if you push a PR.

**Comment by gballesteros10** [comment]
copy that. thanks @warengonzaga!

**Comment by gballesteros10** [comment]
hi @warengonzaga and @jofftiquez 

i pushed a new commit. i planned to do this on another PR after this one, but decided to add it now since we're waiting.

for your checking and preview deployment approval. thanks!

**Comment by RupertAvery** [comment]
Can you make the Share to facebook button use white on  #4267b3?

**Comment by gballesteros10** [comment]
thanks @RupertAvery ! tried it, color looks better.

and since we're improving the styling a bit anyway, i went ahead and added the logo.

![2023-04-21 16_18_57-My Philippines Travel Level](https://user-images.githubusercontent.com/19832210/233582680-2cf71fde-033c-4c30-95f4-9904b6daabdc.png)

**Comment by RupertAvery** [comment]
Awesome, thanks!
